runner:
  phpmd:
    cmd: ./vendor/bin/phpmd . checkstyle phpmd.ruleset.xml --exclude 'cache/*,vendor/*,rector.php,.php-cs-fixer.*' --baseline-file phpmd.baseline.xml
    name: phpmd
    format: checkstyle
    level: warning

  phpstan:
    cmd: ./vendor/bin/phpstan analyze --error-format=checkstyle --configuration=phpstan.neon.dist
    format: checkstyle
    name: phpstan
    level: warning

  psalm:
    cmd: ./vendor/bin/psalm --config=psalm.xml --no-progress --use-baseline=psalm-baseline.xml --output-format=checkstyle
    format: checkstyle
    name: psalm
    level: warning