runner:
  phpmd:
    cmd: phpmd . checkstyle phpmd.ruleset.xml --exclude 'cache/*,vendor/*,rector.php,.php-cs-fixer.*' --baseline-file phpmd.baseline.xml
    name: phpmd
    format: checkstyle
    level: warning

  phpstan:
    cmd: phpstan --error-format=checkstyle
    format: checkstyle
    name: phpstan
    level: warning

  psalm:
    cmd: psalm --config=psalm.xml --no-progress --use-baseline=psalm-baseline.xml --output-format=checkstyle
    format: checkstyle
    name: psalm
    level: warning

#  php-cs-fixer:
#    cmd: php-cs-fixer fix --config=.php-cs-fixer.php --allow-risky=yes --using-cache=no --no-interaction --show-progress=none --ansi --dry-run --format=checkstyle
#    format: checkstyle
#    name: php-cs-fixer
#    level: warning