name: ReviewDog
on:
  push:
    branches:
#      - master
      - develop
    paths:
      - 'src/**'
      - 'wp-duplicate-post.php'
  pull_request:
    paths:
      - 'src/**'
      - 'wp-duplicate-post.php'
  workflow_call:

jobs:
  reviewdog:
    name: reviewdog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          extensions: igbinary
          coverage: none
          tools: phpmd, psalm, phpstan

      - id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-

      - run: composer install --prefer-dist --no-interaction --no-progress -o

      - name: Setup reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Reviewdog GitHub Check
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ github.token }}
        run: reviewdog -reporter=github-check -filter-mode=diff_context -fail-on-error